import * as React from 'react';
import Head from 'next/head';

import MainNavbar from 'src/components/Navbar';
import HomePageSvg from 'src/svgs/homePageSVG';

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Web Development solutions for growing businesses</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <MainNavbar />
        <section>
          {/* <div className="bg-gradient-to-t from-blue-300 dark:from-blue-900 to-transparent w-full h-full absolute left-0 top-0 block -z-10"></div> */}
          <div>
            <img
              className="w-full h-full absolute top-0 -z-20 bg-cover "
              src="/3.png"
              alt=""
            />
          </div>
          <div className="px-4 sm:px-6 md:px-8 md:mt-32 ">
            <div className="relative max-w-5xl mx-auto py-20 px-5 bg-white filter backdrop-blur-lg bg-opacity-40 rounded-3xl shadow-2xl">
              <h1 className="text-slate-900 font-extrabold text-4xl lg:text-5xl tracking-tight text-center">
                <span className="text-slate-800 dark:text-white">
                  We are here to make your business look good
                </span>{' '}
                <span className="text-transparent bg-clip-text bg-gradient-to-br from-blue-500 via-cyan-500 to-pink-400">
                  online.
                </span>
              </h1>
              <p className="mt-6 text-base text-slate-700 md:text-lg lg:text-xl text-center max-w-3xl mx-auto">
                {' '}
                Offering scalable and modern web development solutions with the
                latest technology to let your business have a unique online
                representation.{' '}
              </p>
            </div>
          </div>
        </section>
      </div>
    </React.Fragment>
  );
}
