import * as React from 'react';
import Head from 'next/head';

import MainNavbar from 'src/components/Navbar';
import HomePageSvg from 'src/svgs/homePageSVG';

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Web Development solutions for growing businesses</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="bg-[url('/backgrounds/31.png')] h-screen bg-center">
        <MainNavbar />
        <section>
          <div className="px-4 sm:px-6 mt-20 md:px-8 md:mt-40 ">
            <div className="relative max-w-5xl mx-auto py-20 px-5 bg-white filter backdrop-blur-lg bg-opacity-40 rounded-3xl shadow-2xl">
              <h1 className="text-slate-900 font-extrabold text-4xl lg:text-5xl tracking-tight text-center">
                <span className="text-slate-800 dark:text-white">
                  We are here to make your business look good
                </span>{' '}
                <span className="text-transparent bg-clip-text bg-gradient-to-br from-blue-500 via-cyan-500 to-pink-400">
                  online.
                </span>
              </h1>
              <p className="mt-8 text-base text-slate-700 md:text-lg lg:text-xl text-center max-w-3xl mx-auto">
                {' '}
                Offering <span className="font-bold"> scalable </span> &{' '}
                <span className="font-bold">
                  modern web development solutions
                </span>{' '}
                with the latest technology to let your business have a unique
                online representation.{' '}
              </p>
            </div>
          </div>
        </section>
      </div>
    </React.Fragment>
  );
}
